In [14]:
!pip install openpyxl


In [19]:

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
etiketleyici = LabelEncoder().fit(veri.Sınıflar)
etiketler = etiketleyici.transform(veri.Sınıflar)
siniflar = list(etiketleyici.classes_)

# Eğitim verisinin hazırlanması
egitimVerisi = veri.drop(["Sınıflar"],axis=1)

# Verilerin normalleştiriliyor
from sklearn.preprocessing import MinMaxScaler
olcek = MinMaxScaler().fit(egitimVerisi.values)
egitim = olcek.transform(egitimVerisi.values)

# Verisetinin eğitim ve test olarak ayrılması
from sklearn.model_selection import train_test_split
X_egitim, X_test, y_egitim, y_test = train_test_split(egitimVerisi, etiketler, test_size = 0.20)

from sklearn.impute import SimpleImputer
import numpy as np

# NaN değerlerini ortalama ile değiştirerek bir doldurucu Oluşturulması
doldur = SimpleImputer(missing_values=np.nan, strategy='mean')

# Doldurucunun veriye Uygulanması
X_EgitimDolu = doldur.fit_transform(X_egitim)

# SVM modelinin çağrılması
from sklearn import svm

# SVM sınıflandırıcısının Oluşturulması
clf = svm.SVC(kernel='linear')

# SVM modelinin eğitim verisine uygulanması
clf.fit(X_EgitimDolu, y_egitim)

# Test verisinin doldurulması
X_TestDolu= doldur.transform(X_test)

# Tahminlerin yapılması
y_tahmin = clf.predict(X_TestDolu)

# Performans metriklerinin hesaplanması
from sklearn import metrics
dogru = metrics.accuracy_score(y_test, y_tahmin)
f1 = metrics.f1_score(y_test, y_tahmin, average='weighted')
kesin = metrics.precision_score(y_test, y_tahmin, average='weighted', zero_division=0)
duyar= metrics.recall_score(y_test, y_tahmin, average='weighted')
karmasikMatris = metrics.confusion_matrix(y_test, y_tahmin)

# Sonuçların yazdırılması
print(f"Doğruluk: {dogru}")
print(f"F1 Skoru: {f1}")
print(f"Kesinlik: {kesin}")
print(f"Duyarlılık: {duyar}")
print("Karmaşıklık matrisi:\n", karmasikMatris)

# Veri boyutlarının kontrol edilmesi
print("X_test boyutu:", X_test.shape)
print("X_egitim boyutu:", X_egitim.shape)

# Verilerin tekrar boyutlandırılması ve tahminlerin incelenmesi
import numpy as np
X_test = np.array(X_test).reshape(2, 32640, 1)
X_egitim = np.array(X_egitim).reshape(2, 130560, 1)

for i in range(len(X_test)):
    print(X_test[i], y_tahmin[i])

print(X_test[1])
y_tahmin[1]



Doğruluk: 0.9958333333333333
F1 Skoru: 0.9937543493389005
Kesinlik: 0.9916840277777778
Duyarlılık: 0.9958333333333333
Karmaşıklık matrisi:
 [[  0   0   1]
 [  0   0   1]
 [  0   0 478]]
X_test boyutu: (480, 136)
X_egitim boyutu: (1920, 136)
[[0.0823]
 [0.    ]
 [0.0371]
 ...
 [   nan]
 [   nan]
 [   nan]] 8
[[0.005 ]
 [0.0198]
 [0.005 ]
 ...
 [   nan]
 [   nan]
 [   nan]] 8
[[0.005 ]
 [0.0198]
 [0.005 ]
 ...
 [   nan]
 [   nan]
 [   nan]]


8